application: thetravelerbook
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: main.application
 
- url: /css
  mime_type: text/css
  static_dir: static/css

- url: /js
  mime_type: text/javascript
  static_dir: static/js
  
- url: /img/(.*\.(gif|png|jpg|jpeg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg|jpeg))
  
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico


libraries:

- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"
  
