application: gcdc2013-thetravelerbook
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  mime_type: text/css
  static_dir: static/css

- url: /js
  mime_type: text/javascript
  static_dir: static/js
  
- url: /img/(.*\.(gif|png|jpg|jpeg|svg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg|jpeg|svg))
  
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /.*
  script: main.application

libraries:

- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"
  
- name: markupsafe
  version: "0.15"
  
- name: lxml
  version: '2.3'
  
- name: PIL
  version: "1.1.7"
  
skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*sh
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.template$
- tmp
- tests

